name: Deploy to GitHub Pages

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy wasm_exec.js
        run: docker run -u root -v `pwd`:/repo tinygo/tinygo:0.31.2 /bin/bash -c "cp /usr/local/tinygo/targets/wasm_exec.js /repo/public"
      - name: Build wasm
        run: docker run -u root -v `pwd`:/repo tinygo/tinygo:0.31.2 tinygo build -o /repo/public/mylib.wasm -target wasm --no-debug /repo/main.go
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
